# Configuration File
---
# Root directory of videos
video: "path/to/folder/or.mp4"

# Output directory for embeddings
output: "/path/to/output/folder"

# Probability that the transform will happen [0.0 - 1.0]
transform_prob: 0.1

# Number of frames to use for each temporal crop
frame_length: 16

# Remove the first frame from each scene to account for scene detection errors
tidy_start: False

...
